### ISSUE TITLE
iOS build is not created  

### ISSUE THREAD

**Issue by vitulgoyani** [greensopinion/asset_webview#2] opened 2022-05-04 10:49 UTC
i make build using "flutter build ios --release" and it is show me error

fatal error: module 'asset_webview' not found
    @import asset_webview;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

    Result bundle written to path:
        /var/folders/wk/smm6mfxn6dd6rcv8vjtj49qr0000gn/T/flutter_tools.bL005N/flutter_ios_build_temp_dirAuCAgn/temporary_xcresult_bundle


Parse Issue (Xcode): Module 'asset_webview' not found

**Comment by greensopinion** [comment] 2022-05-04 14:53
Could you provide the output of `flutter pub get` from your project, the output of `flutter doctor -v` and a copy of your `pubspec.yaml`

**Comment by vitulgoyani** [comment] 2022-05-12 09:40
![Screenshot 2022-05-12 at 3 07 33 PM](https://user-images.githubusercontent.com/27543719/168041029-0e763ec8-11a0-4b78-8200-35ffac10816f.png)

---------------------------------------------------

[✓] Flutter (Channel stable, 2.10.5, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.10.5 at /Users/vitul/Documents/Software/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/vitul/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • iPhone 8 (mobile) • C165026F-5E97-4421-B917-2B3441358221 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 101.0.4951.54

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

--------------------------------------



environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  page_view_indicators: ^2.0.0
  auto_size_text: ^2.1.0
  url_launcher: ^6.0.8
  webview_flutter: ^3.0.1
  shared_preferences: ^2.0.6
  dio: ^4.0.0
  cached_network_image: ^3.0.0
  flutter_cached_pdfview:
  asset_webview: ^0.0.5

**Comment by greensopinion** [comment] 2022-05-21 03:35
Sorry, I'm not sure what the issue is. It works fine for me, so perhaps there is something specific to your project.
You may want to check the indentation of your `pubspec.yaml`

**Comment by vitulgoyani** [comment] 2022-05-23 09:53
- flutter build ios --release 
this command get error

**Comment by greensopinion** [comment] 2022-05-23 14:33
Where are you running the command? Are you running it from your own project? If you could provide an example that would be helpful. e.g. if you put a sample project that reproduces the error on github I'll be able to take a look.

**Comment by greensopinion** [comment] 2022-07-29 17:41
Closing due to lack of repeatable steps to reproduce the issue. Feel free to provide more information.

**Closed as completed by greensopinion** 2022-07-29 17:41 UTC
